<?php

namespace AppBundle\Repository;

/**
 * CareerConsultantFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareerConsultantFormRepository extends \Doctrine\ORM\EntityRepository
{
}
