<?php

namespace AppBundle\Repository;

/**
 * ClassListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassListRepository extends \Doctrine\ORM\EntityRepository
{
}
