<?php

namespace AppBundle\Repository;

/**
 * EntityNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityNameRepository extends \Doctrine\ORM\EntityRepository
{
}
