<?php

namespace AppBundle\Repository;

/**
 * FacultyLiaisonFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultyLiaisonFormRepository extends \Doctrine\ORM\EntityRepository
{
}
