<?php

namespace AppBundle\Repository;

/**
 * FacultyLiaisonListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultyLiaisonListRepository extends \Doctrine\ORM\EntityRepository
{
}
