<?php

namespace AppBundle\Repository;

/**
 * HRFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HRFormRepository extends \Doctrine\ORM\EntityRepository
{
}
