<?php

namespace AppBundle\Repository;

/**
 * InternationalOfficeFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternationalOfficeFormRepository extends \Doctrine\ORM\EntityRepository
{
}
