<?php

namespace AppBundle\Repository;

/**
 * InternDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternDataRepository extends \Doctrine\ORM\EntityRepository
{
}
