<?php

namespace AppBundle\Repository;

/**
 * SiteSupervisorFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteSupervisorFormRepository extends \Doctrine\ORM\EntityRepository
{
}
