<?php

namespace AppBundle\Repository;

/**
 * StudentFormTwoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentFormTwoRepository extends \Doctrine\ORM\EntityRepository
{
}
