<?php

namespace AppBundle\Repository;

/**
 * StudentFormOneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentFormOneRepository extends \Doctrine\ORM\EntityRepository
{
}
