<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQun9sqb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQun9sqb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQun9sqb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQun9sqb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQun9sqb\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Qun9sqb',
    'container.build_id' => '7f7bf52b',
    'container.build_time' => 1523748111,
));
