<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU251tgx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU251tgx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerU251tgx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerU251tgx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerU251tgx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'U251tgx',
    'container.build_id' => '716bf4a9',
    'container.build_time' => 1523404072,
));
