<?php
// Autotmatically generated by Symfony. Adjusted by Catherine Guilbaud
// In this class, if the user is not signed in, we assume that they're the site supervisor attempting to access the page
// A "login" page is generated for them where they input an access code that was generated in the student form one. That access code will automatically
// select the student form. This removes the ability of the site supervisor to choose a student form at will.
// If the user is signed in, they can view the list of applications for their particular access level.
namespace AppBundle\Controller;

use AppBundle\Entity\SiteSupervisorForm;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

/**
 * Sitesupervisorform controller.
 *
 * @Route("sitesupervisorform")
 */
class SiteSupervisorFormController extends Controller
{
    private $accessCode;
    private $studentFormOneData;
    private $studentFormOne;
    private $studentFormOneID;
    /**
     * Lists all siteSupervisorForm entities.
     *
     * @Route("/", name="sitesupervisorform_index")
     * @Method({"GET", "POST"})
     */
    public function indexAction(Request $request)
    {
        
        if ($this->getUser() && $this->get('security.authorization_checker')->isGranted('ROLE_SUPER_ADMIN')) {
            
            $em = $this->getDoctrine()->getManager();
            
            $flQuery2 = $em->createQuery("SELECT sfo.id, sfo.firstName, sfo.lastName, sfo.emailAddress, sfo.cWID, sfo.submitDate as lastUpdated FROM AppBundle:StudentFormOne sfo LEFT JOIN AppBundle:SiteSupervisorForm ssf WITH sfo.id = ssf.student_form_one WHERE ssf.student_form_one IS NULL ORDER BY lastUpdated ASC"); 
            
            $studentFormOnesOnly = $flQuery2->getResult();
            
            $siteSupervisorForms = $em->getRepository('AppBundle:SiteSupervisorForm')->findAll();
            
            return $this->render('sitesupervisorform/adminindex.html.twig', array(
                'studentFormOnesOnly' => $studentFormOnesOnly,
                'siteSupervisorForms' => $siteSupervisorForms,
            ));
            
        }else{
            
            $em = $this->getDoctrine()->getManager();
    
            $data = array();
            $form = $this->createFormBuilder($data)
                ->add('email', EmailType::class)
                ->add('accessCodeSS', PasswordType::class)
                ->add('submit', SubmitType::class)
                ->getForm();
    
            $form->handleRequest($request);
            
            if ($form->isSubmitted() && $form->isValid()) {
                $accessCode = $form["accessCodeSS"]->getData();
    
                return $this->redirectToRoute('sitesupervisorform_new');
            }
            
            return $this->render('sitesupervisorform/index.html.twig', array(
                    'form' => $form->createView(),
            ));
        }
    }

    /**
     * Creates a new siteSupervisorForm entity.
     *
     * @Route("/new", name="sitesupervisorform_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request, \Swift_Mailer $mailer)
    {
        if(isset($_GET["accessCodeSS"])){
    
            $this->accessCode = $_GET["accessCodeSS"];
    
            $accessCode = $this->accessCode;
            $em = $this->getDoctrine()->getManager();
                
            $query = $em->createQuery('SELECT u FROM AppBundle:StudentFormOne u WHERE u.siteSuperAccessCode = :accessCode')
                ->setParameter('accessCode', $accessCode);
            $studentFormOneID = $query->getResult();
            
            $this->studentFormOneData = $studentFormOneID;

            $this->studentFormOne = $studentFormOneID[0];
            
            $query = $em->createQuery('SELECT u.firstName, u.lastName FROM AppBundle:StudentFormOne u WHERE u.siteSuperAccessCode = :accessCode')
                ->setParameter('accessCode', $accessCode);
            $studentData = $query->getResult();
            
            $studentFormOne = $studentData[0];
            
        }
        
        $siteSupervisorForm = new SiteSupervisorForm($this->studentFormOne);

        $form = $this->createForm('AppBundle\Form\SiteSupervisorFormType', $siteSupervisorForm);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($siteSupervisorForm);
            $em->flush();
            
            $studentFName = $this->studentFormOne->getFirstName();
            $studentLName = $this->studentFormOne->getLastName();
            $studentEmail = $this->studentFormOne->getEmailAddress();
            
            $studentFormTwoURL = "http://18.233.91.151:8080/WinthropInternship/web/app_dev.php/studentformtwo";
            
            $message = (new \Swift_Message('Successful Submission of Winthrop Internship Site Supervisor Form'))
                ->setFrom('cce@winthrop.edu')
                ->setTo($studentEmail)
                ->setBody(
                    $this->renderView(
                        'emails/SiteSupervisorForm/student_notifcation.html.twig',
                        array('studentFName' => $studentFName,
                              'studentFormTwoURL' => $studentFormTwoURL,
                        )
                    ),
                    'text/html'
                )
                ->addPart(
                    $this->renderView(
                        'emails/SiteSupervisorForm/student_notification.txt.twig',
                        array('studentFName' => $studentFName,
                              'studentFormTwoURL' => $studentFormTwoURL,
                        )
                    ),
                    'text/plain'
                );
            $mailer->send($message);

            return $this->redirectToRoute('sitesupervisorform_show', array('id' => $siteSupervisorForm->getId()));
        }
    
            return $this->render('sitesupervisorform/new.html.twig', array(
                'studentFormOne' => $studentFormOne,
                'siteSupervisorForm' => $siteSupervisorForm,
                'form' => $form->createView(),
            ));
    }

    /**
     * Finds and displays a siteSupervisorForm entity.
     *
     * @Route("/{id}", name="sitesupervisorform_show")
     * @Method("GET")
     */
    public function showAction(SiteSupervisorForm $siteSupervisorForm)
    {
        $deleteForm = $this->createDeleteForm($siteSupervisorForm);

        return $this->render('sitesupervisorform/show.html.twig', array(
            'siteSupervisorForm' => $siteSupervisorForm,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing siteSupervisorForm entity.
     *
     * @Route("/{id}/edit", name="sitesupervisorform_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, SiteSupervisorForm $siteSupervisorForm)
    {
        $deleteForm = $this->createDeleteForm($siteSupervisorForm);
        $editForm = $this->createForm('AppBundle\Form\SiteSupervisorFormType', $siteSupervisorForm);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('sitesupervisorform_edit', array('id' => $siteSupervisorForm->getId()));
        }

        return $this->render('sitesupervisorform/edit.html.twig', array(
            'siteSupervisorForm' => $siteSupervisorForm,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a siteSupervisorForm entity.
     *
     * @Route("/{id}", name="sitesupervisorform_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, SiteSupervisorForm $siteSupervisorForm)
    {
        $form = $this->createDeleteForm($siteSupervisorForm);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($siteSupervisorForm);
            $em->flush();
        }

        return $this->redirectToRoute('sitesupervisorform_index');
    }

    /**
     * Creates a form to delete a siteSupervisorForm entity.
     *
     * @param SiteSupervisorForm $siteSupervisorForm The siteSupervisorForm entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(SiteSupervisorForm $siteSupervisorForm)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('sitesupervisorform_delete', array('id' => $siteSupervisorForm->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}
