# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
            # id: fos_user.user_provider.username
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_SUPER_MOD_ADMIN: [ROLE_SUPER_ADMIN]

    firewalls:
        main:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
                provider: fos_userbundle
                # always_use_default_target_path: false
                default_target_path:            /studentformone
            logout:
                path: /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
